/**
 * Extracts just the ~25 brand glyphs the stack graph needs from simple-icons
 * into `src/data/logos.ts`.
 *
 * simple-icons ships 3457 icons; importing it at runtime would either bloat the
 * bundle or lean on tree-shaking that is easy to break. Generating a small
 * committed file instead keeps the client payload to exactly what we render,
 * and keeps `simple-icons` a devDependency.
 *
 *   node scripts/gen-logos.mjs
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const ICONS = path.join(process.cwd(), 'node_modules', 'simple-icons', 'icons');

/** node id -> simple-icons slug candidates, first hit wins. */
const MAP = {
  react: ['react'],
  next: ['nextdotjs'],
  ts: ['typescript'],
  tailwind: ['tailwindcss'],
  rn: ['react'], // simple-icons has no separate React Native mark
  framer: ['framer', 'framermotion'],
  zustand: ['zustand'],
  tanstack: ['reactquery', 'tanstack'],
  zod: ['zod'],
  nuqs: [],
  rhf: ['reacthookform'],
  node: ['nodedotjs'],
  express: ['express'],
  ws: [], // WebSockets is a protocol, not a brand — Socket.io's mark would be wrong
  electron: ['electron'],
  builder: ['electronbuilder'],
  webauthn: [],
  mongo: ['mongodb'],
  postgres: ['postgresql'],
  aws: [], // Amazon's marks are not carried by simple-icons
  actions: ['githubactions'],
  docker: ['docker'],
  crypto: [],
  jwt: ['jsonwebtokens'],
  oauth: [], // Auth0/OpenID are vendors, not OAuth itself
};

const pick = async (slugs) => {
  for (const slug of slugs) {
    const file = path.join(ICONS, `${slug}.svg`);
    try {
      const svg = await fs.readFile(file, 'utf8');
      const d = svg.match(/\sd="([^"]+)"/)?.[1];
      const title = svg.match(/<title>([^<]+)<\/title>/)?.[1] ?? slug;
      if (d) return { slug, d, title };
    } catch {}
  }
  return null;
};

const out = {};
const missing = [];

for (const [id, slugs] of Object.entries(MAP)) {
  if (!slugs.length) {
    missing.push(id);
    continue;
  }
  const hit = await pick(slugs);
  if (hit) out[id] = hit;
  else missing.push(id);
}

const body = `// GENERATED by scripts/gen-logos.mjs — do not edit by hand.
// Brand glyphs from simple-icons (CC0 for the SVG data; the marks themselves
// remain trademarks of their respective owners, used here nominatively to
// indicate technologies worked with).
//
// Nodes with no brand mark available fall back to a letter monogram:
// ${missing.join(', ') || 'none'}

export type Logo = { d: string; title: string };

export const logos: Record<string, Logo> = {
${Object.entries(out)
  .map(([id, v]) => `  ${id}: {\n    title: ${JSON.stringify(v.title)},\n    d: ${JSON.stringify(v.d)},\n  },`)
  .join('\n')}
};

/** simple-icons paths are all authored on a 24x24 grid. */
export const LOGO_VIEWBOX = '0 0 24 24';
`;

await fs.writeFile(path.join(process.cwd(), 'src', 'data', 'logos.ts'), body);

console.log(`wrote ${Object.keys(out).length} logos`);
console.log(`monogram fallback: ${missing.join(', ')}`);
